version: "3.5"

services:
  load_balancer:
    image: shashwot/nginx-more
    restart: always
    network_mode: "host"
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - "./etc/load_balancer/default.conf:/etc/nginx/nginx.conf"
      - "./etc/load_balancer/GeoLite2-Country.mmdb:/var/lib/GeoIP/GeoLite2-Country.mmdb"

  worker_uk:
    image: nginx:alpine
    restart: always
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - "./etc/worker/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web/index_uk.html:/var/www/html/public/index.html"

  worker_us_1:
    image: nginx:alpine
    restart: always
    ports:
      - "127.0.0.1:8002:80"
    volumes:
      - "./etc/worker/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web/index_us_1.html:/var/www/html/public/index.html"

  worker_us_2:
    image: nginx:alpine
    restart: always
    ports:
      - "127.0.0.1:8003:80"
    volumes:
      - "./etc/worker/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web/index_us_2.html:/var/www/html/public/index.html"

  worker_other:
    image: nginx:alpine
    restart: always
    ports:
      - "127.0.0.1:8004:80"
    volumes:
      - "./etc/worker/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web/index_other.html:/var/www/html/public/index.html"

  worker_backup:
    image: nginx:alpine
    restart: always
    ports:
      - "127.0.0.1:8005:80"
    volumes:
      - "./etc/worker/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web/index_backup.html:/var/www/html/public/index.html"
